### ISSUE TITLE
Animation: Hit Effect

### ISSUE THREAD

**Issue by starls51** [BreakoutInteractive/RogueSpace#25]
Design/Sprites/Effects/hit_01.png

This animation should play at the center (image_width/2, image_height/2) of a character sprite when they receive a hit. This is feedback to show that the player successfully hit an enemy. For the time being, this can also be used to show when the player character receives a hit.

(I did not plan a specific length for this animation, but it should play fast. Will work on adding timing instructions for future anims)

**Comment by mtamor3629** [comment]
applied to enemy only on my branch. see pr
