### ISSUE TITLE
Pressing pause button causes player to attack

### ISSUE THREAD

**Issue by starls51** [BreakoutInteractive/RogueSpace#26]

**Comment by zyc2024** [comment]
resolved. The fix is that button events come first before the game input registers the touch SO we can flag that the UI button has been clicked on and prevent the screen input from being fed into the main game.

**Comment by zyc2024** [comment]
resolved. The fix is that button events come first before the game input registers the touch SO we can flag that the UI button has been clicked on and prevent the screen input from being fed into the main game.
