### ISSUE TITLE
Ranged Indicator does not reflect true range

### ISSUE THREAD

**Issue by zyc2024** [BreakoutInteractive/RogueSpace#71]
In particular, in the event of having no collisions, the length of the indicator should roughly reflect the maximum distance that can be traveled by the projectile. 

This requires that the projectiles are killed by distance as opposed to time. Since the projectile is updating its lifespan every frame by getting the elapsed time of its animation but the physics may get updated 0 times in a given frame, this creates a misalignment between anticipated distance (time * speed) vs actual distance covered.

**Comment by mtamor3629** [comment]
Done. Although the distance thing might have caused some minor issues, I think that the bigger problem was that I did not initialize the variable "loc" before raycasting, so it was getting treated as the vector (0,0) when there were no hits.
